/* AUTHENTICATION */
// Signup
export const AUTH_SIGNUP = "AUTH_SIGNUP";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILURE = "AUTH_SIGNUP_FAILURE";
// Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
// Check sessions
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
// Logout
export const AUTH_LOGOUT = "AUTH_LOGOUT";

/* MAINPAGE */
// Lastest
export const MAIN_LASTEST = "MAIN_LASTEST";
export const MAIN_LASTEST_SUCCESS = "MAIN_LASTEST_SUCCESS";
export const MAIN_LASTEST_FAILURE = "MAIN_LASTEST_FAILURE";
// Recommend
export const MAIN_RECOMMEND = "MAIN_RECOMMEND";
export const MAIN_RECOMMEND_SUCCESS = "MAIN_RECOMMEND_SUCCESS";
export const MAIN_RECOMMEND_FAILURE = "MAIN_RECOMMEND_FAILURE";
// Like
export const MAIN_LIKE = "MAIN_LIKE";
export const MAIN_LIKE_SUCCESS = "MAIN_LIKE_SUCCESS";
export const MAIN_LIKE_FAILURE = "MAIN_LIKE_FAILURE";

/* CLIENTINFO */
export const CLIENTIFO_SET = "CLIENTIFO_SET";
export const CLIENTIFO_SENDACT = "CLIENTIFO_SENDACT";
export const CLIENTIFO_RECVACT = "CLIENTIFO_RECVACT";

// NameChange
export const NAME_CHANGE = "NAME_CHANGE";
export const NAME_CHANGE_SUCCESS = "NAME_CHANGE_SUCCESS";
export const NAME_CHANGE_FAILURE = "NAME_CHANGE_FAILURE";

